version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
